services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=naduvani-farm'
      - 'MYSQL_PASSWORD=sa'
      - 'MYSQL_ROOT_PASSWORD=sa'
      - 'MYSQL_USER=sa'
    ports:
      - '3306'
