spring:
  application:
    name: naduvani-farm-product-services

  datasource:
    url: jdbc:mysql://localhost:3306/naduvani_farm
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
