server:
  port: 8081
spring:
  application:
    name: naduvani-farm-product-services
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://${MYSQL_CONTAINER_HOST}:${MYSQL_CONTAINER_PORT}/testdb
    username: testuser
    password: testpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
